# Generated by Django 4.2.10 on 2025-12-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_alter_productmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSliderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='عدد کوچکتر اول نمایش داده می\u200cشود', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_sliders', to='shop.productmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول اسلایدر اصلی',
                'verbose_name_plural': 'محصولات اسلایدر اصلی',
                'ordering': ['order', '-created_date'],
            },
        ),
    ]
